alias apocng="kubectl get pod -l app=apocng-k8spray -o jsonpath='{.items[0].metadata.name}'"
export TI=k8sprayorg/ansible-terraform
alias ansible-terraform="kubectl run -ti --image=$TI ansible-terraform --command /bin/sh"

# cat /root/aws.env | python -c 'import sys, yaml, json; y=yaml.load(sys.stdin.read()); print json.dumps(y)' | curl -k -X POST -d@- https://apocng-k8spray/api/store2/2017/
# curl -k https://apocng-k8spray/api/store2/2017/
